minReadLength=15
adapter=TGAGATCGGAAGAGCGGTTCAG

../flexbar-3.5.0-linux/flexbar -n 3 -t x00 -r ../tmp/x00.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x01 -r ../tmp/x01.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x02 -r ../tmp/x02.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x03 -r ../tmp/x03.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x04 -r ../tmp/x04.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x05 -r ../tmp/x05.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x06 -r ../tmp/x06.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x07 -r ../tmp/x07.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x08 -r ../tmp/x08.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
../flexbar-3.5.0-linux/flexbar -n 3 -t x09 -r ../tmp/x09.fastq.gz --zip-output GZ --barcodes ../barcodes.fasta --barcode-unassigned --barcode-trim-end LTAIL --barcode-error-rate 0 --adapter-seq $adapter --adapter-trim-end RIGHT --adapter-error-rate 0.1 --adapter-min-overlap 1 --min-read-length $minReadLength --umi-tags --length-dist &
